# Synchronize Node Parameters

rosbag_folder_path: "/mnt/c/Users/uctsh/OneDrive - University of Cape Town/Documents/MASTERS/EXPERIMENTAL WORK/Calibration/Stereo Inertial Calibration/stereo inertial calibration 2" # /path/to/folder
unsynched_bag_name: "Stereo_Inertial_Calibration_2.bag" # bagName.bag
cam0_topic: "/video_source_0/raw"
cam1_topic: "/video_source_1/raw"
imu_topic: "/imu/data"